version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: .
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url": "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
          "spring.datasource.username": "$MYSQLDB_USER",
          "spring.datasource.password": "$MYSQLDB_ROOT_PASSWORD",
          "spring.datasource.driver-class-name": "com.mysql.jdbc.Driver",
          "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQLDialect",
          "spring.jpa.hibernate.ddl-auto": "update",
          "ayou7995.openapi.dev-url": "http://localhost:8080",
          "ayou7995.openapi.prod-url": "https://ayou7995-api.com",
          "springdoc.swagger-ui.path": "/swagger-documentation",
          "springdoc.api-docs.path": "/swagger-api-docs",
          "springdoc.packages-to-scan": "com.ayou7995.javalearning.controller",
          "springdoc.swagger-ui.tryItOutEnabled": "false",
          "springdoc.swagger-ui.operationsSorter": "method",
          "springdoc.swagger-ui.tagsSorter": "alpha",
          "springdoc.swagger-ui.filter": "true",
          "logging.level.org.springframework.web": "DEBUG",
          "logging.level.org.springdoc": "DEBUG"
        }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
